name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]  # Changed from 'master' to 'main' (GitHub default)
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository Configurations ######
          app_location: "client"          # Path to your frontend code
          api_location: "server/api"      # Path to your Azure Functions
          output_location: "build"        # React's build folder
          ###### End of Repository Configurations ######

      # Removed unnecessary OIDC and PR closing steps
